### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cplex': 'cplex'

### ISSUE THREAD

**Issue by mengshanfeng** [spcl/absinthe#1]
Hi,  @gysit :
I am running your code, however, in the "**Optimization**" part: 

Once the parameters are set we can run the optimization to generate different optimization variants.
```
python ./fastwaves.py -e -g -f ./fastwaves
python ./advection.py -e -g -f ./advection
python ./diffusion.py -e -g -f ./diffusion

when i run the above 3 cmds, the **following errors occur**, looking forward to your help!

/absinthe-master$ python ./diffusion.py -e -g -f ./diffusion
-> working dir: diffusion/
-> optimize: False
-> explore: True
-> auto: False
-> run generation: True
-> run compilation: False
-> optimizing sequence ['ulap', 'ufli', 'uflj', 'uout', 'vlap', 'vfli', 'vflj', 'vout', 'wlap', 'wfli', 'wflj', 'wout', 'pplap', 'ppfli', 'ppflj', 'ppout']
Traceback (most recent call last):
  File "./diffusion.py", line 363, in <module>
    main(argv[1:])
  File "./diffusion.py", line 337, in main
    explore_space(experiments, folder)
  File "./diffusion.py", line 149, in explore_space
    optimize_program(folder + name, experiments[name])
  File "/absinthe-master/stencil_optimizer.py", line 1012, in optimize_program
    solve_lp(name)
  File "/absinthe-master/stencil_optimizer.py", line 798, in solve_lp
    proc = Popen(["cplex"], stdin=PIPE)
  File "/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
**FileNotFoundError: [Errno 2] No such file or directory: 'cplex': 'cplex'**

**Comment by gysit** [comment]
@mengshanfeng 

Ah yes, you need to have a working installation of cplex (the IBM ILP solver). If you work for an academic institution you can get a free license otherwise it is expensive software.

https://developer.ibm.com/docloud/blog/2019/03/12/cplex-optimization-studio-12-9-is-available/

An alternative could be the scip solver

https://en.wikipedia.org/wiki/SCIP_(optimization_software)

If you want to run scip you need the adapt the python script to call scip instead of cplex. However, cplex is preferable since it likely runs faster and converges for larger problems.

Best,
Tobias

**Comment by mengshanfeng** [comment]
@gysit 
many thanks, i will try this.
Best,
icurry

**Comment by mengshanfeng** [comment]
@gysit 
i tried the free edition, however, it seemed that sth went wrong:
**CPLEX> CPLEX Error  1016: Community Edition. Problem size limits exceeded.**
meanwhile, i failed to download the academic edition.
so i wonder i f you have one?
Best,
curry

**Comment by gysit** [comment]
@mengshanfeng
Absinthe generates fairly large optimization problems and the free edition seems to be limited to small problem sizes. I registered for their academic program:

https://developer.ibm.com/docloud/blog/2019/07/04/cplex-optimization-studio-for-students-and-academics/

If I remember correctly this takes a moment since they want to verify that you really work for a university.
